version: '3.8'

services:
  freeswitch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: freeswitch
    volumes:
      - freeswitch_data:/usr/local/freeswitch
    ports:
    - "5060:5060"              # SIP
    - "5080:5080"              # Alternate SIP
    - "16385-32769:16384-32768" # RTP (changed starting port to avoid conflicts)
    environment:
      - TIMEZONE=UTC
    restart: unless-stopped

volumes:
  freeswitch_data:
    driver: local
